#!/usr/bin/env bash
# scripts/mobile-dev.sh — one command to run the mobile app against a local
# `make bootstrap` cluster (Tier A: NOTIFIER=dev, SSE delivery, no cloud push).
#
# It:
#   1. detects this host's LAN IP (the phone reaches the host by it),
#   2. ensures the mobile-gateway is deployed and the registry has its templates
#      (a registry restart wipes the in-memory store — the usual e2e-breaker),
#   3. opens the needed firewall ports (best-effort, ufw only),
#   4. starts LAN-bound port-forwards for the gateway + dashboard/OIDC origin,
#   5. writes mobile/.env.local pointing the app at this host, and
#   6. starts the Expo dev server (Metro). Ctrl+C tears the port-forwards down.
#
# One-time prerequisites NOT done here (see plans/mobile-ciba/testing-plan.md):
#   - a dev build installed on the device (eas build / eas device:create),
#   - `npm install` in mobile/ (auto-run here if node_modules is missing).
#
# Override any port or the IP via env, e.g.:  LAN_IP=192.168.1.50 make mobile-dev
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

GW_PORT="${GW_PORT:-8091}"          # gateway public surface (/me/* + SSE)
DASH_PORT="${DASH_PORT:-18090}"     # dashboard + proxied OIDC; 18090 dodges VS Code's auto-forwarded 8090
METRO_PORT="${METRO_PORT:-8081}"    # Expo/Metro dev server
KIND_CLUSTER="${KIND_CLUSTER:-agent-platform}"

# --- 1. LAN IP ---------------------------------------------------------------
LAN_IP="${LAN_IP:-$(ip route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}')}"
if [ -z "${LAN_IP:-}" ]; then
  echo "ERROR: couldn't detect a LAN IP. Re-run as: LAN_IP=<your-host-ip> $0" >&2
  exit 1
fi
echo "==> Host LAN IP: $LAN_IP   (phone must be on the same Wi-Fi)"

kubectl get ns >/dev/null 2>&1 || { echo "ERROR: kubectl can't reach the cluster. Bring it up with 'make bootstrap'." >&2; exit 1; }

# --- 2. ensure gateway deployed + templates seeded ---------------------------
if ! kubectl get deploy mobile-gateway >/dev/null 2>&1; then
  echo "==> mobile-gateway not deployed — building its image and applying manifests (first run)..."
  docker build --target mobile-gateway -t agent-mobile-gateway:latest .
  kind load docker-image agent-mobile-gateway:latest --name "$KIND_CLUSTER"
  kubectl apply -f deploy/manifests/
fi
kubectl rollout status deploy/mobile-gateway --timeout=120s

# Reseed only if templates are gone (cheap check via a throwaway port-forward).
kubectl port-forward svc/registry 18080:8080 >/dev/null 2>&1 &
reg_pf=$!
sleep 2
templates="$(curl -fsS http://localhost:18080/v1/templates 2>/dev/null || echo '?')"
kill "$reg_pf" 2>/dev/null || true
if [ "$templates" = "[]" ]; then
  echo "==> registry has no templates (restart wiped the in-memory store) — reseeding..."
  make reseed
else
  echo "==> registry templates present"
fi

# --- 3. firewall (best-effort, ufw only) -------------------------------------
if command -v ufw >/dev/null 2>&1 && sudo -n true 2>/dev/null && sudo ufw status 2>/dev/null | grep -q "Status: active"; then
  echo "==> ufw active — opening $METRO_PORT/$GW_PORT/$DASH_PORT"
  for p in "$METRO_PORT" "$GW_PORT" "$DASH_PORT"; do sudo ufw allow "$p"/tcp >/dev/null 2>&1 || true; done
elif command -v ufw >/dev/null 2>&1 && sudo ufw status 2>/dev/null | grep -q "Status: active"; then
  echo "!! ufw is active but passwordless sudo isn't available. If the phone can't connect, run:"
  echo "     sudo ufw allow $METRO_PORT/tcp && sudo ufw allow $GW_PORT/tcp && sudo ufw allow $DASH_PORT/tcp"
fi

# --- 4. LAN-bound port-forwards (torn down on exit) --------------------------
pids=()
cleanup() {
  echo; echo "==> stopping port-forwards"
  for p in "${pids[@]:-}"; do pkill -P "$p" 2>/dev/null || true; kill "$p" 2>/dev/null || true; done
}
trap cleanup EXIT INT TERM

forward() {  # name hostport
  ( while true; do kubectl port-forward --address 0.0.0.0 "svc/$1" "$2:8080" >/dev/null 2>&1 || true; sleep 1; done ) &
  pids+=($!)
}
echo "==> port-forwarding gateway→0.0.0.0:$GW_PORT, dashboard→0.0.0.0:$DASH_PORT"
forward mobile-gateway "$GW_PORT"
forward dashboard "$DASH_PORT"
sleep 3
curl -fsS "http://localhost:$GW_PORT/health" >/dev/null 2>&1 && echo "   gateway healthy on $GW_PORT" || echo "   WARN: gateway not answering on $GW_PORT yet"
curl -sS -o /dev/null "http://localhost:$DASH_PORT/" 2>/dev/null || true; echo "   dashboard reachable on $DASH_PORT (401 at / is expected)"

# --- 5. generate mobile/.env.local -------------------------------------------
cat > mobile/.env.local <<EOF
# Generated by scripts/mobile-dev.sh on $(date -u +%FT%TZ) — local dev (Tier A, SSE).
# Host LAN IP: $LAN_IP. Regenerated each run; gitignored.
EXPO_PUBLIC_GATEWAY_URL=http://$LAN_IP:$GW_PORT
EXPO_PUBLIC_ISSUER=http://$LAN_IP:$DASH_PORT
EXPO_PUBLIC_AUTH_ENDPOINT=http://$LAN_IP:$DASH_PORT/connect/authorize
EXPO_PUBLIC_TOKEN_ENDPOINT=http://$LAN_IP:$DASH_PORT/connect/token
EXPO_PUBLIC_CLIENT_ID=mobile
EXPO_PUBLIC_ALLOW_CLEARTEXT=true
EOF
echo "==> wrote mobile/.env.local"

# --- 6. start Expo (Metro) ---------------------------------------------------
[ -d mobile/node_modules ] || (echo "==> installing mobile deps..." && cd mobile && npm install)
echo "==> starting Expo on :$METRO_PORT — open the Spawnly dev build on your phone."
echo "    Then: log in as alice → spawn a chain-worker from the dashboard → approve on the phone."
cd mobile && npx expo start --dev-client --host lan --port "$METRO_PORT"
