apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: agent-workloads
spec:
  className: "spire-system-spire"
  spiffeIDTemplate: 'spiffe://cluster.local/agent/{{ index .PodMeta.Labels "tenant-id" }}/{{ index .PodMeta.Labels "user-id" }}/{{ index .PodMeta.Labels "agent-type" }}/{{ index .PodMeta.Labels "agent-id" }}'
  podSelector:
    matchLabels:
      agent-platform.io/managed: "true"
  workloadSelectorTemplates:
    - "k8s:ns:default"
